# Generated by Django 4.1.2 on 2022-10-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
