# Generated by Django 4.1.2 on 2022-10-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.CharField(max_length=200),
        ),
    ]
