# Generated by Django 4.1.2 on 2022-10-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_post_public_alter_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.JSONField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
