# Generated by Django 4.1.2 on 2022-10-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_post_tag_album_post_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='public',
        ),
        migrations.AddField(
            model_name='album',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
