# Generated by Django 4.1.2 on 2022-10-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_remove_post_owner_remove_post_public_album_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='album',
        ),
    ]
