# Generated by Django 4.1.2 on 2022-10-27 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_remove_post_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.album'),
            preserve_default=False,
        ),
    ]
