# Generated by Django 4.1.2 on 2022-10-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_post_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/{album.name}'),
        ),
    ]
