# Generated by Django 4.1.2 on 2022-10-27 22:48

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=gallery.models.get_upload_path),
        ),
    ]
