# Generated by Django 4.1.2 on 2022-10-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
