# Generated by Django 4.1.2 on 2022-10-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_rename_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='album',
            field=models.ForeignKey(blank=True, limit_choices_to={'owner': 'auth.User'}, on_delete=django.db.models.deletion.CASCADE, to='gallery.album'),
        ),
    ]
