# Generated by Django 4.1.2 on 2022-10-29 11:43

from django.db import migrations
import gallery.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_album_description_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=gallery.models.get_upload_path),
        ),
    ]
